version: '3'
services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres:latest
    environment:
      - POSTGRES_DB=MYDB2
      - POSTGRES_PASSWORD=admin2
      - POSTGRES_USER=admin2
    restart: always
